<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';
function db(): PDO {
 static $pdo=null;
 if($pdo) return $pdo;
 $config=db_config();
 if(empty($config['name']) || empty($config['user'])) throw new RuntimeException('Die Datenbank ist nicht konfiguriert. Bitte DB_NAME und DB_USER in .env eintragen.');
 $dsn=sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s',$config['host'],$config['port'],$config['name'],$config['charset']);
 $pdo=new PDO($dsn,$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
 return $pdo;
}
function e(?string $s): string { return htmlspecialchars($s ?? '', ENT_QUOTES, 'UTF-8'); }
function base_url(): string { $p=rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? ''),'/\\'); return $p==='.'?'':$p; }
function site_url(string $path=''): string { return base_url().($path ? '/'.ltrim($path,'/') : ''); }
function asset(string $path): string { return site_url($path); }
function redirect(string $url): never { header('Location: '.$url); exit; }
function csrf(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(24)); return $_SESSION['csrf']; }
function check_csrf(): void { if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')) { http_response_code(400); exit('Ungültige Anfrage.'); } }
function logged_in(): bool { return !empty($_SESSION['admin_id']); }
function require_login(): void { if(!logged_in()) redirect(site_url('admin/login.php')); }
function flash(?string $set=null): ?string { if($set!==null){$_SESSION['flash']=$set; return null;} $v=$_SESSION['flash']??null; unset($_SESSION['flash']); return $v; }
function init_db(): void {
 $pdo=db();
 $pdo->exec("CREATE TABLE IF NOT EXISTS admins(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(190) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at VARCHAR(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS settings(id TINYINT UNSIGNED PRIMARY KEY, site_title VARCHAR(255), intro TEXT, phone VARCHAR(100), email VARCHAR(255), address TEXT, facebook VARCHAR(255), instagram VARCHAR(255), vimeo VARCHAR(255), youtube VARCHAR(255), impressum TEXT, privacy TEXT, logo VARCHAR(500), hero_image VARCHAR(500)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS pages(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) UNIQUE NOT NULL, title VARCHAR(255) NOT NULL, eyebrow VARCHAR(255), intro TEXT, body LONGTEXT, image VARCHAR(500), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS fields(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, short_text TEXT, body LONGTEXT, image VARCHAR(500), accent VARCHAR(30) DEFAULT 'orange', published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS projects(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(255), year VARCHAR(20), short_text TEXT, body LONGTEXT, image VARCHAR(500), video_url VARCHAR(500), status VARCHAR(30) DEFAULT 'aktuell', published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS offers(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(255), target VARCHAR(255), duration VARCHAR(255), short_text TEXT, body LONGTEXT, image VARCHAR(500), contact VARCHAR(255), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS team(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, role VARCHAR(255), bio LONGTEXT, image VARCHAR(500), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS funders(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, logo VARCHAR(500), url VARCHAR(500), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS partners(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, logo VARCHAR(500), url VARCHAR(500), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $pdo->exec("CREATE TABLE IF NOT EXISTS awards(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, year VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, image VARCHAR(500), url VARCHAR(500), published TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 if((int)$pdo->query('SELECT COUNT(*) FROM settings')->fetchColumn()===0) $pdo->exec("INSERT INTO settings(id,site_title,intro,phone,email,address,facebook,instagram,vimeo,youtube,impressum,privacy,logo,hero_image) VALUES(1,'Young Images e.V.','Junge Menschen machen Medien.','0157 718 953 20','info@youngimages.de','Dortustraße 46\n14467 Potsdam','','','','','Young Images – Verein für Medien und Bildung e.V.\nDortustraße 46\n14467 Potsdam','Die Datenschutzerklärung wird vor Veröffentlichung final geprüft.','assets/young-images-logo.png','assets/images/young-people-filming.jpg')");
 $pages=[
 ['home','Startseite','MEDIEN. KULTUR. ZUKUNFT.','Junge Menschen machen Medien.','Young Images verbindet Filmbildung, kulturelle Bildung und Medienbildung. Wir ermöglichen jungen Menschen, ihre Ideen zu entwickeln, kreativ umzusetzen und mit anderen zu teilen.','assets/images/about.jpg'],
 ['about','Über uns','ÜBER UNS','Gemeinsam Medien gestalten.','Young Images e.V. ist ein Verein für Medien und Bildung. Wir arbeiten mit Kindern und Jugendlichen, schaffen Räume für kreative Medienpraxis und verbinden Bildung, Kultur und gesellschaftliche Themen. Unsere Arbeit stärkt Eigeninitiative, Teamgeist, Teilhabe und kritisches Denken.','assets/images/about.jpg'],
 ['offers','Angebote','UNSERE ANGEBOTE','Formate, die zu Menschen und Ideen passen.','Workshops, Fort- und Weiterbildungen sowie medienpädagogische Beratung: Unsere Angebote können von Schulen, Einrichtungen, Gruppen und Partnern angefragt und gemeinsam angepasst werden.','assets/images/field-film.jpg'],
 ['fields','Arbeitsfelder','UNSERE ARBEITSFELDER','Vielfältige Perspektiven für eine starke Gesellschaft.','Filmbildung, Kulturelle Bildung und Medienbildung bilden den Kern unserer Arbeit. Ergänzend entwickeln wir Angebote für inklusive Medienarbeit und medienpädagogische Beratung und Begleitung.','assets/images/field-media.jpg'],
 ['projects','Projekte','PROJEKTE','Ideen werden Wirklichkeit.','Von Ferienprojekten bis zu Schulangeboten: In unseren Projekten entstehen Filme, Clips, Musik und neue Perspektiven.','assets/images/project-mediensommer.jpg'],
 ['team','TEAM','WER WIR SIND','Menschen hinter den Projekten.','Unser Team verbindet pädagogische Erfahrung, Medienpraxis, Kulturarbeit und die Lust, gemeinsam mit jungen Menschen neue Ideen umzusetzen.','assets/images/about.jpg'],
 ['funders','Förderer','FÖRDERER','Unterstützung, die Wirkung möglich macht.','Unsere Arbeit wird durch Förderer und öffentliche sowie gemeinnützige Partner unterstützt.','assets/images/field-culture.jpg'],
 ['partners','Partner','PARTNER','Gemeinsam mehr bewegen.','Wir arbeiten mit Bildungseinrichtungen, Kulturorten, Medienpartnern und Fachleuten zusammen.','assets/images/field-film.jpg'],
 ['awards','Auszeichnungen','AUSZEICHNUNGEN','Engagement, das sichtbar wird.','Eine wachsende Sammlung von Auszeichnungen, Urkunden und Anerkennungen. Die Einträge werden chronologisch gepflegt.','assets/images/project-clips.jpg'],
 ['contact','Kontakt','KONTAKT','Lust auf ein Medienprojekt?','Du möchtest ein Angebot buchen, ein Projekt anfragen oder mit Young Images zusammenarbeiten? Wir freuen uns auf deine Nachricht.','assets/images/about.jpg']
 ];
 $ins=$pdo->prepare('INSERT IGNORE INTO pages(slug,title,eyebrow,intro,body,image,published,sort_order) VALUES(?,?,?,?,?,?,1,?)'); foreach($pages as $i=>$p)$ins->execute([...$p,$i]);
 if((int)$pdo->query('SELECT COUNT(*) FROM fields')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO fields(title,short_text,body,image,accent,published,sort_order) VALUES(?,?,?,?,?,1,?)');$data=[['Filmbildung','Eigene Geschichten erzählen. Kreativ, praktisch, wirkungsvoll.','Mit Kamera, Ton und Schnitt entwickeln Kinder und Jugendliche eigene Geschichten und lernen, filmische Mittel bewusst einzusetzen.','assets/images/field-film.jpg','orange'],['Kulturelle Bildung','Kultur erleben. Gestalten. Teilhabe ermöglichen.','Kulturelle Ausdrucksformen werden zum Ausgangspunkt für eigene Ideen, Perspektiven und gemeinsames Gestalten.','assets/images/field-culture.jpg','cyan'],['Medienbildung','Medien verstehen. Chancen nutzen. Verantwortung übernehmen.','Wir machen Medien zum Gegenstand und zum Werkzeug: kritisch, kreativ und alltagsnah.','assets/images/field-media.jpg','lime'],['Medienpädagogische Beratung & Begleitung','Einrichtungen sicher und kreativ begleiten.','Wir unterstützen pädagogische Einrichtungen bei medienpädagogischen Konzepten, Projekten und Entwicklungsprozessen.','assets/images/about.jpg','orange'],['Inklusive Medienarbeit','Teilhabe durch Medien ermöglichen.','Wir entwickeln Medienangebote, die unterschiedliche Voraussetzungen berücksichtigen und möglichst vielen jungen Menschen Teilhabe ermöglichen.','assets/images/field-culture.jpg','cyan']]; foreach($data as $i=>$r)$ins->execute([...$r,$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM projects')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO projects(title,category,year,short_text,body,image,video_url,status,published,sort_order) VALUES(?,?,?,?,?,?,?,?,1,?)');$data=[['Musikworkshop','MUSIK / MEDIEN','2026','Musik, Bild und Ausdruck werden zu einer gemeinsamen Produktion.','In kreativen Workshops entwickeln Jugendliche Ideen, probieren Medien aus und verbinden Musik mit Bildsprache.','assets/images/project-musikworkshop.jpg','','aktuell'],['MeMi','MEDIENBILDUNG','2026','Medien verstehen, ausprobieren und gemeinsam reflektieren.','MeMi steht für praktische Medienbildung: Jugendliche arbeiten an eigenen Ideen und setzen sich gleichzeitig kritisch mit Medien und ihrer Wirkung auseinander.','assets/images/project-memi.jpg','','aktuell'],['Mediensommer','FERIENPROJEKT','2026','Ferienzeit wird zur kreativen Medienwerkstatt.','Im Mediensommer entstehen in einer intensiven Ferienwoche eigene Medienproduktionen. Von der Idee über Dreh und Ton bis zum fertigen Clip arbeiten die Teilnehmenden gemeinsam.','assets/images/project-mediensommer.jpg','','aktuell'],['Clips n’ Rap','FILMBILDUNG','2025','Rap, Kamera und Schnitt treffen auf eigene Geschichten.','Bei Clips n’ Rap verbinden junge Menschen musikalischen Ausdruck mit Film. Sie entwickeln Texte, drehen Szenen und schneiden daraus ihre eigenen Clips.','assets/images/project-clips.jpg','','archiv']]; foreach($data as $i=>$r)$ins->execute([...$r,$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM offers')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO offers(title,category,target,duration,short_text,body,image,contact,published,sort_order) VALUES(?,?,?,?,?,?,?,?,1,?)');$data=[['Medienworkshop Schule','SCHULE','3.–6. Klasse','1–5 Projekttage','Film, Video und Medien praktisch kennenlernen.','Wir planen Workshops passend zu Alter, Thema und Rahmenbedingungen der Schule.','assets/images/field-film.jpg','Young Images'],['Medienworkshop Freizeit','FREIZEIT','Kinder & Jugendliche','1–3 Tage','Kreativ produzieren und gemeinsam Spaß haben.','Ferien, Jugendhaus oder Gruppe: Wir bringen Methoden und Technik mit und entwickeln gemeinsam ein passendes Format.','assets/images/project-mediensommer.jpg','Young Images'],['Fort- und Weiterbildung','FORTBILDUNG','Pädagogische Fachkräfte','nach Absprache','Medienpädagogik praxisnah und direkt einsetzbar.','Fortbildungen zu Film, Medienbildung, KI und medienpädagogischer Praxis – individuell für Teams und Einrichtungen.','assets/images/field-media.jpg','Young Images'],['Medienpädagogische Beratung','BERATUNG','Pädagogische Einrichtungen','nach Absprache','Von der Idee bis zur Umsetzung.','Wir beraten und begleiten Einrichtungen bei medienpädagogischen Konzepten, Projekten und Entwicklungsprozessen.','assets/images/about.jpg','Young Images']];foreach($data as $i=>$r)$ins->execute([...$r,$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM team')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO team(name,role,bio,image,published,sort_order) VALUES(?,?,?,?,1,?)');$names=[['Kristin','Vorstand / Medienbildung','Organisation, Projekte und pädagogische Arbeit.'],['Claudia','Vorstand / Kultur','Kulturelle Bildung und Projektentwicklung.'],['Andreas','Vorstand / Medien & KI','Medienpraxis, Technik und neue Themen.'],['Albrecht','Film & Medienproduktion','Konzeption, Filmproduktion und Projektumsetzung.'],['Chantal','Medienpädagogik','Workshops und kreative Medienarbeit.'],['Susanne','Projektentwicklung','Konzepte, Projekte und Bildungsarbeit.'],['Isabell','Medienpädagogik','Kreative Workshops und Begleitung.'],['James','Film & Workshop','Filmische Praxis und Gruppenarbeit.'],['Jakob','Medienarbeit','Produktion und medienpädagogische Praxis.'],['Josefine','Kulturelle Bildung','Kulturelle Projekte und kreative Formate.']];foreach($names as $i=>$r)$ins->execute([$r[0],$r[1],$r[2],'assets/images/about.jpg',$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM funders')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO funders(name,description,logo,url,published,sort_order) VALUES(?,?,?,?,1,?)');$names=['Aktion Mensch','Medienanstalt Berlin-Brandenburg','Landespräventionsrat Brandenburg','MBJS – Ministerium für Bildung, Jugend und Sport Brandenburg','Mein Land – Meine Zukunft','Kultur macht Stark','Plattform Kulturelle Bildung Brandenburg – Kulturland Brandenburg','Brandenburgische Landeszentrale für Politische Bildung','Stiftung Toleranz (FC Flick Stiftung)'];foreach($names as $i=>$n)$ins->execute([$n,'Förderer von Young Images.','',$n==='Aktion Mensch'?'https://www.aktion-mensch.de':'',$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM partners')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO partners(name,description,logo,url,published,sort_order) VALUES(?,?,?,?,1,?)');$names=['Filmmuseum Potsdam','Treffpunkt Freizeit Potsdam','Begegnungsstätte Schloss Gollwitz','Landesfachverband Medienbildung Brandenburg','Hamburger Volkshochschule','Mehrgenerationenhaus Nuthetal'];foreach($names as $i=>$n)$ins->execute([$n,'Kooperationspartner und Fachpartner.','','',$i]);}
 if((int)$pdo->query('SELECT COUNT(*) FROM awards')->fetchColumn()===0){$ins=$pdo->prepare('INSERT INTO awards(year,title,description,image,url,published,sort_order) VALUES(?,?,?,?,?,1,?)');$data=[['2026','Anerkennung und Engagement','Beispielhafter Eintrag – Urkunde kann im Backend ersetzt werden.','assets/images/project-clips.jpg',''],['2025','Auszeichnung für Medienbildung','Beispielhafter Eintrag – bitte mit Originalurkunde ersetzen.','assets/images/project-mediensommer.jpg',''],['2024','Projektpreis','Beispielhafter Eintrag für die neue Galerie.','assets/images/project-memi.jpg','']];foreach($data as $i=>$r)$ins->execute([...$r,$i]);}
}
function q(string $sql,array $params=[]): array {$st=db()->prepare($sql);$st->execute($params);return $st->fetchAll(PDO::FETCH_ASSOC);}
function one(string $sql,array $params=[]): ?array {$r=q($sql,$params);return $r[0]??null;}
function setting(string $key): string { $r=one('SELECT * FROM settings WHERE id=1'); return (string)($r[$key]??''); }
function save_upload(string $field): ?string { if(empty($_FILES[$field])||$_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return null; $f=$_FILES[$field]; if($f['error']!==UPLOAD_ERR_OK||$f['size']>MAX_UPLOAD)throw new RuntimeException('Upload fehlgeschlagen oder Datei zu groß.'); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']); $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif','application/pdf'=>'pdf']; if(!isset($allowed[$mime]))throw new RuntimeException('Nur JPG, PNG, WEBP, GIF oder PDF sind erlaubt.'); if(!is_dir(UPLOAD_DIR))mkdir(UPLOAD_DIR,0755,true); $name=date('Ymd_His').'_'.bin2hex(random_bytes(4)).'.'.$allowed[$mime]; move_uploaded_file($f['tmp_name'],UPLOAD_DIR.$name); return 'uploads/'.$name; }
function page_by_slug(string $slug): array { return one('SELECT * FROM pages WHERE slug=? AND published=1',[$slug]) ?? []; }
