<?php require_once __DIR__.'/functions.php'; init_db();
$slug=$_GET['page']??'home'; $valid=['home','fields','projects','offers','about','team','funders','partners','awards','contact']; if(!in_array($slug,$valid,true))$slug='home';
$s=one('SELECT * FROM settings WHERE id=1'); $page=page_by_slug($slug); $fields=q('SELECT * FROM fields WHERE published=1 ORDER BY sort_order,id'); $projects=q("SELECT * FROM projects WHERE published=1 ORDER BY CASE status WHEN 'aktuell' THEN 0 ELSE 1 END, sort_order,id"); $offers=q('SELECT * FROM offers WHERE published=1 ORDER BY sort_order,id'); $team=q('SELECT * FROM team WHERE published=1 ORDER BY sort_order,id'); $funders=q('SELECT * FROM funders WHERE published=1 ORDER BY sort_order,id'); $partners=q('SELECT * FROM partners WHERE published=1 ORDER BY sort_order,id'); $awards=q('SELECT * FROM awards WHERE published=1 ORDER BY year DESC,sort_order,id');
function nav_active($s,$x){return $s===$x?' class="active"':'';} ?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($page['title']??'Young Images')?></title><link rel="stylesheet" href="<?=asset('css/site.css')?>"></head><body><div class="site">
<header><a class="logo" href="<?=site_url()?>"><img src="<?=asset($s['logo'])?>" alt="Young Images"></a><nav><a<?=nav_active($slug,'fields')?> href="<?=site_url('index.php?page=fields')?>">Arbeitsfelder</a><a<?=nav_active($slug,'projects')?> href="<?=site_url('index.php?page=projects')?>">Projekte</a><a<?=nav_active($slug,'about')?> href="<?=site_url('index.php?page=about')?>">Über uns</a><a<?=nav_active($slug,'funders')?> href="<?=site_url('index.php?page=funders')?>">Förderer &amp; Partner</a><a<?=nav_active($slug,'awards')?> href="<?=site_url('index.php?page=awards')?>">Auszeichnungen</a><a<?=nav_active($slug,'contact')?> href="<?=site_url('index.php?page=contact')?>">Kontakt</a></nav></header>
<?php if($slug==='home'): ?>
<section class="hero"><div class="hero-copy"><div class="eyebrow"><?=e($page['eyebrow'])?></div><h1>Junge Menschen<br><strong>machen Medien.</strong></h1><div class="line orange-line"></div><p><?=e($page['body'])?></p><a class="link" href="<?=site_url('index.php?page=about')?>">Mehr über uns <b>→</b></a><span class="star lime-star">✱</span><svg class="scribble left" viewBox="0 0 190 180"><path d="M0 25 C70 0 15 65 63 77 C116 90 35 119 78 134 C118 148 142 170 190 170"/></svg></div><div class="hero-media"><div class="blob hero-blob"></div><div class="hero-photo" style="background-image:url('<?=asset($s['hero_image'])?>')"></div><svg class="scribble right" viewBox="0 0 120 190"><path d="M110 5 C65 28 105 59 76 75 C46 92 87 112 56 132 C31 148 29 165 2 185"/></svg></div><div class="tags"><span class="tag orange-tag">▰ &nbsp;Kreativ.</span><span class="tag blue-tag">♟ &nbsp;Kritisch.</span><span class="tag lime-tag">♥ &nbsp;Gemeinsam.</span></div></section>
<section class="work"><div class="work-image-wrap"><div class="blob work-blob"></div><div class="work-photo" style="background-image:url('<?=asset($fields[0]['image']??$s['hero_image'])?>')"></div></div><div class="work-content"><div class="eyebrow">UNSERE ARBEITSFELDER</div><h2>Vielfältige Perspektiven<br>für eine starke Gesellschaft.</h2><p><?=e($page_by_fields=page_by_slug('fields')['body']??'')?></p><div class="fields"><?php foreach(array_slice($fields,0,3) as $i=>$f): ?><article><div class="number <?=e($f['accent'])?>-under">0<?=($i+1)?></div><h3><?=e($f['title'])?></h3><small><?=nl2br(e($f['short_text']))?></small></article><?php endforeach; ?></div><a class="link work-link" href="<?=site_url('index.php?page=fields')?>">Alle Arbeitsfelder <b>→</b></a></div></section>
<section class="projects"><div class="section-head"><div><div class="eyebrow">AKTUELLE PROJEKTE</div><h2>Ideen werden Wirklichkeit.</h2></div><a class="link" href="<?=site_url('index.php?page=projects')?>">Alle Projekte ansehen <b>→</b></a></div><div class="project-grid"><?php foreach(array_slice(array_values(array_filter($projects,fn($p)=>$p['status']==='aktuell')),0,4) as $i=>$p): ?><a class="project" href="<?=site_url('index.php?page=projects')?>#p<?=e((string)$p['id'])?>"><div class="p-photo" style="background-image:url('<?=asset($p['image'])?>')"></div><div class="p-bottom"><div><h3><?=e($p['title'])?></h3><small><?=e($p['category'])?></small></div><span class="arrow <?=['orange-bg','blue-bg','lime-bg','orange-bg'][$i]?>">→</span></div></a><?php endforeach; ?></div></section>
<section class="statement"><svg class="bottom-scribble" viewBox="0 0 260 150"><path d="M0 128 C100 120 22 100 83 83 C151 63 67 42 138 27 C190 17 220 22 258 0"/></svg><div class="idea">IDEEN.<br>MENSCHEN.<br>WIRKUNG.<span></span></div><blockquote>„Medien sind mehr als Technik –<br>sie sind ein Raum für neue Perspektiven.“</blockquote><div class="line orange-line"></div><a class="button" href="<?=site_url('index.php?page=offers')?>">Angebote entdecken <b>→</b></a></section>
<?php else: ?>
<section class="inner-hero"><div><div class="eyebrow"><?=e($page['eyebrow']??'YOUNG IMAGES')?></div><h1><?=e($page['intro']??$page['title'])?></h1><div class="line orange-line"></div><p><?=e($page['body']??'')?></p></div><div class="inner-image"><div class="blob"></div><img src="<?=asset($page['image']??$s['hero_image'])?>" alt=""></div></section>
<?php if($slug==='fields'): ?><section class="cards-section"><div class="card-grid field-grid"><?php foreach($fields as $f): ?><article class="big-card"><img src="<?=asset($f['image'])?>" alt=""><div><div class="eyebrow">ARBEITSFELD</div><h2><?=e($f['title'])?></h2><p><?=nl2br(e($f['body']))?></p></div></article><?php endforeach; ?></div></section>
<?php elseif($slug==='projects'): ?><section class="cards-section"><div class="project-list"><?php foreach($projects as $p): ?><article class="detail-card" id="p<?=e((string)$p['id'])?>"><img src="<?=asset($p['image'])?>" alt=""><div><div class="eyebrow"><?=e($p['category'])?> · <?=e($p['year'])?></div><h2><?=e($p['title'])?></h2><p class="lead"><?=e($p['short_text'])?></p><p><?=nl2br(e($p['body']))?></p><?php if($p['video_url']): ?><a class="link" href="<?=e($p['video_url'])?>" target="_blank" rel="noopener">Video ansehen <b>→</b></a><?php endif; ?></div></article><?php endforeach; ?></div></section>
<?php elseif($slug==='offers'): ?><section class="cards-section"><div class="offer-grid"><?php foreach($offers as $o): ?><article class="offer-card"><img src="<?=asset($o['image'])?>" alt=""><div class="eyebrow"><?=e($o['category'])?></div><h2><?=e($o['title'])?></h2><p class="lead"><?=e($o['short_text'])?></p><p><?=nl2br(e($o['body']))?></p><div class="meta"><b>Zielgruppe:</b> <?=e($o['target'])?> · <b>Dauer:</b> <?=e($o['duration'])?></div><a class="button" href="<?=site_url('index.php?page=contact')?>">Angebot anfragen <b>→</b></a></article><?php endforeach; ?></div></section>
<?php elseif($slug==='team'): ?><section class="cards-section"><div class="team-grid"><?php foreach($team as $t): ?><article class="person"><img src="<?=asset($t['image'])?>" alt=""><div class="eyebrow"><?=e($t['role'])?></div><h2><?=e($t['name'])?></h2><p><?=e($t['bio'])?></p></article><?php endforeach; ?></div></section>
<?php elseif($slug==='funders'||$slug==='partners'): $arr=$slug==='funders'?$funders:$partners; ?><section class="cards-section"><div class="logo-grid"><?php foreach($arr as $x): ?><article class="logo-card"><?php if($x['logo']): ?><img src="<?=asset($x['logo'])?>" alt="<?=e($x['name'])?>"><?php else: ?><div class="logo-placeholder">YI</div><?php endif; ?><h2><?=e($x['name'])?></h2><p><?=e($x['description'])?></p><?php if($x['url']): ?><a class="link" href="<?=e($x['url'])?>" target="_blank" rel="noopener">Website <b>→</b></a><?php endif; ?></article><?php endforeach; ?></div></section>
<?php elseif($slug==='awards'): ?><section class="cards-section"><div class="award-grid"><?php foreach($awards as $a): ?><article class="award"><img src="<?=asset($a['image'])?>" alt=""><div><div class="eyebrow"><?=e($a['year'])?></div><h2><?=e($a['title'])?></h2><p><?=e($a['description'])?></p></div></article><?php endforeach; ?></div></section>
<?php elseif($slug==='contact'): ?><section class="contact-section"><div class="contact-box"><div class="eyebrow">KONTAKT</div><h2>Wir freuen uns auf deine Nachricht.</h2><p><?=nl2br(e($s['intro']))?></p><p><strong><?=e($s['address'])?></strong><br><?=e($s['email'])?><br><?=e($s['phone'])?></p><a class="button" href="mailto:<?=e($s['email'])?>">E-Mail schreiben <b>→</b></a></div><div class="contact-image"><img src="<?=asset($page['image'])?>" alt=""></div></section>
<?php else: ?><section class="text-section"><p class="lead"><?=nl2br(e($page['body']))?></p></section><?php endif; ?>
<?php endif; ?>
<footer><div class="footer-top"><a class="logo" href="<?=site_url()?>"><img src="<?=asset($s['logo'])?>" alt="Young Images"></a><div class="footer-nav"><a href="<?=site_url('index.php?page=fields')?>">Arbeitsfelder</a><a href="<?=site_url('index.php?page=projects')?>">Projekte</a><a href="<?=site_url('index.php?page=about')?>">Über uns</a><a href="<?=site_url('index.php?page=offers')?>">Angebote</a><a href="<?=site_url('index.php?page=contact')?>">Kontakt</a></div><div class="social"><?php if($s['instagram']): ?>IG<?php endif; ?> <?php if($s['vimeo']): ?>V<?php endif; ?> <?php if($s['youtube']): ?>YT<?php endif; ?></div></div><div class="footer-bottom"><span>© <?=date('Y')?> Young Images e.V.</span><span><a href="<?=site_url('index.php?page=contact')?>">Impressum</a>　 Datenschutz</span></div></footer></div></body></html>
