<?php require_once __DIR__.'/../functions.php'; init_db(); require_login();
$defs=[
'pages'=>['label'=>'Seiten','title'=>'title','fields'=>[['title','Titel','text'],['eyebrow','Eyebrow','text'],['intro','Einleitung','text'],['body','Text','textarea'],['image','Bildpfad','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'fields'=>['label'=>'Arbeitsfelder','title'=>'title','fields'=>[['title','Titel','text'],['short_text','Kurztext','textarea'],['body','Beschreibung','textarea'],['image','Bildpfad','text'],['accent','Akzent (orange/cyan/lime)','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'offers'=>['label'=>'Angebote','title'=>'title','fields'=>[['title','Titel','text'],['category','Kategorie','text'],['target','Zielgruppe','text'],['duration','Dauer','text'],['short_text','Kurztext','textarea'],['body','Beschreibung','textarea'],['image','Bildpfad','text'],['contact','Ansprechperson','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'projects'=>['label'=>'Projekte','title'=>'title','fields'=>[['title','Titel','text'],['category','Kategorie','text'],['year','Jahr','text'],['short_text','Kurztext','textarea'],['body','Beschreibung','textarea'],['image','Bildpfad','text'],['video_url','Video URL','text'],['status','Status (aktuell/archiv)','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'team'=>['label'=>'Team','title'=>'name','fields'=>[['name','Name','text'],['role','Rolle','text'],['bio','Kurzbiografie','textarea'],['image','Bildpfad','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'funders'=>['label'=>'Förderer','title'=>'name','fields'=>[['name','Name','text'],['description','Beschreibung','textarea'],['logo','Logo/Bildpfad','text'],['url','Website','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'partners'=>['label'=>'Partner','title'=>'name','fields'=>[['name','Name','text'],['description','Beschreibung','textarea'],['logo','Logo/Bildpfad','text'],['url','Website','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
'awards'=>['label'=>'Auszeichnungen','title'=>'title','fields'=>[['year','Jahr','text'],['title','Titel','text'],['description','Beschreibung','textarea'],['image','Urkunde/Bildpfad','text'],['url','Website','text'],['published','Veröffentlicht','check'],['sort_order','Reihenfolge','number']]],
];
$section=$_GET['section']??'projects'; if(!isset($defs[$section]))$section='projects';$def=$defs[$section];$edit=(int)($_GET['edit']??0);$err='';
if(isset($_GET['delete'])){if(!hash_equals($_SESSION['csrf']??'',$_GET['csrf']??'')){http_response_code(400);exit('Ungültige Anfrage.');}$id=(int)$_GET['delete'];db()->prepare("DELETE FROM $section WHERE id=?")->execute([$id]);flash('Eintrag gelöscht.');redirect("?section=$section");}
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();try{$id=(int)($_POST['id']??0);$cols=[];$vals=[];foreach($def['fields'] as [$k,$lab,$type]){if($k==='published'){$cols[]=$k;$vals[]=isset($_POST[$k])?1:0;}else{$cols[]=$k;$vals[]=trim((string)($_POST[$k]??''));}}if($id){$set=implode(',',array_map(fn($c)=>"$c=?",$cols));$vals[]=$id;db()->prepare("UPDATE $section SET $set WHERE id=?")->execute($vals);}else{$qs=implode(',',array_fill(0,count($cols),'?'));db()->prepare("INSERT INTO $section (".implode(',',$cols).") VALUES($qs)")->execute($vals);}flash('Gespeichert.');redirect("?section=$section");}catch(Throwable $ex){$err=$ex->getMessage();}}
$row=$edit?one("SELECT * FROM $section WHERE id=?",[$edit]):null;$rows=q("SELECT * FROM $section ORDER BY sort_order,id");$flash=flash();?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($def['label'])?> – Young Images</title><link rel="stylesheet" href="../css/admin.css"></head><body><div class="admin-shell"><aside><img src="../assets/young-images-logo.png" class="admin-logo"><nav><?php foreach($defs as $k=>$v):?><a class="<?=($section===$k?'sel':'')?>" href="?section=<?=$k?>"><?=e($v['label'])?></a><?php endforeach; ?><a href="settings.php">Einstellungen</a><a href="media.php">Medien / Upload</a><a href="../index.php" target="_blank">Website ansehen ↗</a><a href="logout.php">Abmelden</a></nav></aside><main class="admin-main"><div class="admin-head"><div><div class="eyebrow">REDAKTION</div><h1><?=e($def['label'])?></h1></div><a class="view" href="?section=<?=$section?>&amp;edit=0">+ Neu anlegen</a></div><?php if($flash):?><div class="success"><?=e($flash)?></div><?php endif;?><?php if($err):?><div class="error"><?=e($err)?></div><?php endif;?><div class="admin-grid"><section class="panel"><h2><?= $row?'Eintrag bearbeiten':'Neuen Eintrag anlegen' ?></h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="id" value="<?=e((string)($row['id']??0))?>"><?php foreach($def['fields'] as [$k,$lab,$type]):?><label><?=e($lab)?><?php if($type==='textarea'):?><textarea name="<?=e($k)?>" rows="5"><?=e((string)($row[$k]??''))?></textarea><?php elseif($type==='check'):?><span class="check"><input type="checkbox" name="<?=e($k)?>" value="1" <?=!isset($row[$k])||$row[$k]?'checked':''?>> sichtbar</span><?php else:?><input type="<?=$type==='number'?'number':'text'?>" name="<?=e($k)?>" value="<?=e((string)($row[$k]??''))?>"><?php endif;?></label><?php endforeach;?><button>Speichern</button></form></section><section class="panel"><h2>Vorhandene Einträge</h2><?php foreach($rows as $r):?><div class="row"><div><strong><?=e((string)$r[$def['title']])?></strong><small>ID <?=e((string)$r['id'])?> · <?=!empty($r['published'])?'sichtbar':'ausgeblendet'?></small></div><div class="actions"><a href="?section=<?=$section?>&amp;edit=<?=$r['id']?>">Bearbeiten</a><a class="danger" href="?section=<?=$section?>&amp;delete=<?=$r['id']?>&amp;csrf=<?=e(csrf())?>" onclick="return confirm('Wirklich löschen?')">Löschen</a></div></div><?php endforeach;?></section></div></main></div></body></html>
